[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/admin/login"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"
PORT = "1337" 